-- The Trace Manifest — Phase 5E.1 Publication Schema Migration
-- Extends story_clusters with editorial publication fields
-- Adds published_briefings for daily/weekly editorial briefings
-- Run: wrangler d1 execute trace-manifest-db --file=db/migration-5e-publication.sql

-- ============================================================
-- Extend story_clusters with editorial publication fields
-- ============================================================

-- Add stable URL slug (generated from title, unique)
ALTER TABLE story_clusters ADD COLUMN slug TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_story_clusters_slug ON story_clusters(slug);

-- Add editorial content fields
ALTER TABLE story_clusters ADD COLUMN summary TEXT;
ALTER TABLE story_clusters ADD COLUMN editorial_analysis TEXT;
ALTER TABLE story_clusters ADD COLUMN why_it_matters TEXT;
ALTER TABLE story_clusters ADD COLUMN headline_image_url TEXT;

-- Add publication workflow fields
ALTER TABLE story_clusters ADD COLUMN publication_status TEXT NOT NULL DEFAULT 'draft'
  CHECK(publication_status IN ('draft','review','published','withdrawn','superseded'));

-- Migrate existing is_published flag
UPDATE story_clusters SET publication_status = 'published' WHERE is_published = 1;
UPDATE story_clusters SET publication_status = 'draft' WHERE is_published = 0 AND publication_status = 'draft';

-- Add publication timestamp (separate from created_at for editorial tracking)
-- published_at already exists but may be auto-generated; ensure it tracks publication date
-- reviewed_at already exists

-- Add indexes for public read queries
CREATE INDEX IF NOT EXISTS idx_story_clusters_pub_status ON story_clusters(publication_status);
CREATE INDEX IF NOT EXISTS idx_story_clusters_pub_date ON story_clusters(published_at);
CREATE INDEX IF NOT EXISTS idx_story_clusters_topic_pub ON story_clusters(topic, publication_status);

-- ============================================================
-- Published briefings (daily + weekly)
-- ============================================================

CREATE TABLE IF NOT EXISTS published_briefings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  briefing_type TEXT NOT NULL CHECK(briefing_type IN ('daily','weekly')),
  briefing_date TEXT NOT NULL,           -- ISO date (YYYY-MM-DD) for daily, Monday date for weekly
  title TEXT NOT NULL,
  summary TEXT NOT NULL,                 -- Editor's overview paragraph
  content_json TEXT NOT NULL,            -- JSON: array of {story_id, headline, excerpt, commentary}
  publication_status TEXT NOT NULL DEFAULT 'draft'
    CHECK(publication_status IN ('draft','review','published','withdrawn')),
  published_at TEXT,
  reviewed_by TEXT,
  reviewed_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_briefings_type_date ON published_briefings(briefing_type, briefing_date);
CREATE INDEX IF NOT EXISTS idx_briefings_status ON published_briefings(publication_status);
CREATE INDEX IF NOT EXISTS idx_briefings_pub_date ON published_briefings(published_at);

-- ============================================================
-- Auto-generate slugs for existing clusters that lack them
-- ============================================================

-- Simple slug generator: lowercase, alphanumeric + hyphens, trim to 80 chars
-- Run as a one-off after migration:
-- UPDATE story_clusters SET slug = LOWER(REPLACE(REPLACE(REPLACE(TRIM(title), ' ', '-'), '--', '-'), '--', '-')) WHERE slug IS NULL;
-- For now, slugs will be generated by the publish worker module.
