-- Link knowledge document evidence sources
-- Generated by scripts/link-knowledge-sources.mjs

DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-what-is-the-best-closed-model-for-coding-c9db4df8';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('3bd5d5b4-ce5b-449c-b664-11f4575ba20c', 'knowledge-what-is-the-best-closed-model-for-coding-c9db4df8', 'https://openai.com/index/gpt-5-6/', 'source:1', 'external_independent', 'evidence', 'admitted', 'current', 1, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-what-is-the-best-open-weight-model-for-coding-afeb0e13';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('549a8b57-0054-4f67-aac3-35c959b141ab', 'knowledge-what-is-the-best-open-weight-model-for-coding-afeb0e13', 'https://z.ai/blog/glm-5.2', '', 'external_vendor', 'reported_claim', 'quarantined', 'current', 0, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-what-is-the-best-value-coding-model-available-through-an-api-b8444095';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('dd01b5b7-0df0-488a-a7cd-b2d2ce5c1a63', 'knowledge-what-is-the-best-value-coding-model-available-through-an-api-b8444095', 'https://developers.openai.com/api/docs/models', 'source:1', 'external_independent', 'evidence', 'admitted', 'current', 1, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-what-is-the-best-ai-model-for-coding-with-a-very-large-codebase-386857a7';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('d8192f75-074c-4026-b8d7-c3688bdcb865', 'knowledge-what-is-the-best-ai-model-for-coding-with-a-very-large-codebase-386857a7', 'https://developers.openai.com/api/docs/models/gpt-5.6-sol', 'source:1', 'external_independent', 'evidence', 'admitted', 'current', 1, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-which-benchmark-should-be-trusted-when-comparing-ai-coding-models-e9fe7acd';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('2b479527-a4d8-43c1-aa33-9819f437f3fb', 'knowledge-which-benchmark-should-be-trusted-when-comparing-ai-coding-models-e9fe7acd', 'https://openai.com/index/why-we-no-longer-evaluate-swe-bench-verified/', 'source:1', 'external_independent', 'evidence', 'admitted', 'current', 1, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-what-is-the-difference-between-an-ai-coding-assistant-and-an-ai-coding-agent-cc953823';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('76cfc1d3-d6c1-4a38-8129-b06ae4b17c37', 'knowledge-what-is-the-difference-between-an-ai-coding-assistant-and-an-ai-coding-agent-cc953823', 'https://openai.com/index/introducing-codex/', 'source:1', 'external_independent', 'evidence', 'admitted', 'current', 1, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-what-is-the-model-context-protocol-and-when-should-it-be-used-c93ef1b9';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('b9d501c7-fe38-4f7e-a82c-fa1f2b5e7e27', 'knowledge-what-is-the-model-context-protocol-and-when-should-it-be-used-c93ef1b9', 'https://modelcontextprotocol.io/docs/learn/architecture', '', 'external_vendor', 'reported_claim', 'quarantined', 'current', 0, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-how-should-an-ai-coding-agent-be-secured-d3c9c019';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('36cec602-9dca-4a19-897a-2c8e4bb38c8f', 'knowledge-how-should-an-ai-coding-agent-be-secured-d3c9c019', 'https://openai.com/index/running-codex-safely/', 'source:1', 'external_independent', 'evidence', 'admitted', 'current', 1, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-should-an-ai-agent-use-rag-or-fine-tuning-for-private-knowledge-f4da4eaf';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('1254aeac-5e9c-4946-bbd2-7dd9a7dc2fc8', 'knowledge-should-an-ai-agent-use-rag-or-fine-tuning-for-private-knowledge-f4da4eaf', 'https://learn.microsoft.com/en-us/azure/developer/ai/augment-llm-rag-fine-tuning', '', 'external_vendor', 'reported_claim', 'quarantined', 'current', 0, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-can-a-local-open-weight-model-replace-a-frontier-cloud-model-for-coding-a194ede4';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('07537c5d-7b3b-4867-bbcc-ac1e14855afa', 'knowledge-can-a-local-open-weight-model-replace-a-frontier-cloud-model-for-coding-a194ede4', 'https://z.ai/blog/glm-5.2', '', 'external_vendor', 'reported_claim', 'quarantined', 'current', 0, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-what-is-the-best-ai-model-for-web-research-5d0eb429';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('c7a858e6-79b0-4dc5-a378-76a0665cfd38', 'knowledge-what-is-the-best-ai-model-for-web-research-5d0eb429', 'https://openai.com/index/gpt-5-6/', 'source:1', 'external_independent', 'evidence', 'admitted', 'current', 1, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-what-is-an-ai-model-s-context-window-and-is-a-larger-context-window-always-bette-c82be10f';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('61fcfe4a-3cdc-42b1-be4d-70b00bf7e6ea', 'knowledge-what-is-an-ai-model-s-context-window-and-is-a-larger-context-window-always-bette-c82be10f', 'https://developers.openai.com/api/docs/models', 'source:1', 'external_independent', 'evidence', 'admitted', 'current', 1, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-what-is-model-routing-and-why-should-an-ai-system-use-more-than-one-model-01e65407';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('79027d8e-89ab-4acf-9f65-789c56694b02', 'knowledge-what-is-model-routing-and-why-should-an-ai-system-use-more-than-one-model-01e65407', 'https://developers.openai.com/api/docs/models', 'source:1', 'external_independent', 'evidence', 'admitted', 'current', 1, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-when-should-an-ai-agent-require-human-approval-582f8a2b';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('b6789040-cc49-4f45-a9f5-a15ac3d56d12', 'knowledge-when-should-an-ai-agent-require-human-approval-582f8a2b', 'https://openai.github.io/openai-agents-python/human_in_the_loop/', '', 'external_vendor', 'reported_claim', 'quarantined', 'current', 0, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-what-is-prompt-injection-and-how-should-ai-agents-defend-against-it-91c13e5d';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('f003c201-1994-4c44-b048-e205e540ac87', 'knowledge-what-is-prompt-injection-and-how-should-ai-agents-defend-against-it-91c13e5d', 'https://csrc.nist.gov/glossary/term/prompt_injection', '', 'external_vendor', 'reported_claim', 'quarantined', 'current', 0, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-how-should-ai-agents-manage-secrets-credentials-and-identity-b9d24e27';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('65e2634c-4015-4a9d-9d97-f8cae9ab9961', 'knowledge-how-should-ai-agents-manage-secrets-credentials-and-identity-b9d24e27', 'https://www.nccoe.nist.gov/projects/software-and-ai-agent-identity-and-authorization', '', 'external_vendor', 'reported_claim', 'quarantined', 'current', 0, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-should-an-ai-agent-have-persistent-memory-4d484a83';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('56874d66-4b00-4531-b84b-1c5afa901675', 'knowledge-should-an-ai-agent-have-persistent-memory-4d484a83', 'https://openai.github.io/openai-agents-python/sessions/', '', 'external_vendor', 'reported_claim', 'quarantined', 'current', 0, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-how-can-ai-tool-calling-be-made-reliable-6852c808';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('cb1e3fe2-5326-49b1-af3a-9766668782e0', 'knowledge-how-can-ai-tool-calling-be-made-reliable-6852c808', 'https://ai.google.dev/gemini-api/docs/function-calling', 'source:79', 'external_independent', 'evidence', 'admitted', 'current', 1, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-when-should-a-system-use-multiple-ai-agents-instead-of-one-agent-ab9ab0f2';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('837d9571-a08d-405b-aa3c-9fb0d7789e43', 'knowledge-when-should-a-system-use-multiple-ai-agents-instead-of-one-agent-ab9ab0f2', 'https://openai.github.io/openai-agents-python/multi_agent/', '', 'external_vendor', 'reported_claim', 'quarantined', 'current', 0, 'supports');
DELETE FROM knowledge_document_sources WHERE knowledge_document_id = 'knowledge-how-should-multiple-ai-agents-coordinate-and-delegate-work-8d45a76a';
INSERT OR IGNORE INTO knowledge_document_sources
      (id, knowledge_document_id, source_reference, claim_reference, source_kind, source_role, admission_state, freshness_state, independent_evidence_weight, relationship)
      VALUES ('ceecff2f-3d1f-48f3-bf05-fec4212bd782', 'knowledge-how-should-multiple-ai-agents-coordinate-and-delegate-work-8d45a76a', 'https://openai.github.io/openai-agents-python/multi_agent/', '', 'external_vendor', 'reported_claim', 'quarantined', 'current', 0, 'supports');